# deploy to cloud functions
steps:
  # deploy the compiled binary to cloud functions
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
        'functions',
        'deploy',
        'paystack_webhook',
        '--runtime',
        'go121',
        '--trigger-http',
        '--entry-point',
        'PaystackWebhook',
        '--allow-unauthenticated',
        '--source',
        '.' # Deploy the current directory
      ]
